# These are supported funding model platforms

github: Institut-du-Numerique-Responsable
gitlab: 
ko_fi: 
liberapay: institutnr
open_collective: institut-du-numerique-responsable
patreon: 
custom: ['https://institutnr.org/soutenir']
